import KebobModal from "@/components/Modal/KebabModal";
import { Inter } from "next/font/google";
import Head from "next/head";
import AlertModal from "@/components/Modal/AlertModal";
import NewDashBoardModal from "@/components/Modal/NewDashBoardModal";
import ColumnCreateModal from "@/components/Modal/ColumnCreateModal";
import ColumnManagingModal from "@/components/Modal/ColumnManagingModal";
import TodoModal from "@/components/Modal/TodoModal";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodoModal type="edit" />
    </>
  );
}
